In [0]:
/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2022 (16.0.1135)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2022
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

# [dbo].[bids]

In [0]:
USE [smartserve]
GO

In [0]:
/****** Object:  Table [dbo].[bids]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[bids](
	[bid_id] [int] IDENTITY(1,1) NOT NULL,
	[query_id] [int] NOT NULL,
	[restaurant_id] [int] NOT NULL,
	[bid_price] [decimal](10, 2) NOT NULL,
	[estimated_delivery_time] [int] NOT NULL,
	[additional_info] [nvarchar](max) NULL,
	[created_at] [datetime] NULL,
	[status] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[bid_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[bids] TO  SCHEMA OWNER 
GO

# [dbo].[custom_items]

In [0]:
/****** Object:  Table [dbo].[custom_items]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[custom_items](
	[custom_item_id] [int] IDENTITY(1,1) NOT NULL,
	[order_id] [int] NOT NULL,
	[item_name] [varchar](255) NOT NULL,
	[item_description] [nvarchar](max) NULL,
	[quantity] [int] NOT NULL,
	[created_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[custom_item_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[custom_items] TO  SCHEMA OWNER 
GO

# [dbo].[dish_feedback]

In [0]:
/****** Object:  Table [dbo].[dish_feedback]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[dish_feedback](
	[feedback_id] [int] IDENTITY(1,1) NOT NULL,
	[order_detail_id] [int] NOT NULL,
	[rating] [int] NULL,
	[comments] [nvarchar](max) NULL,
	[created_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[feedback_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[dish_feedback] TO  SCHEMA OWNER 
GO

# [dbo].[forgot_password_table]

In [0]:
/****** Object:  Table [dbo].[forgot_password_table]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[forgot_password_table](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[user_id] [int] NULL,
	[token] [nvarchar](max) NULL,
	[time_to_expire] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[forgot_password_table] TO  SCHEMA OWNER 
GO

# [dbo].[order_details]

In [0]:
/****** Object:  Table [dbo].[order_details]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[order_details](
	[order_detail_id] [int] IDENTITY(1,1) NOT NULL,
	[order_id] [int] NOT NULL,
	[item_id] [int] NOT NULL,
	[quantity] [int] NOT NULL,
	[price] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[order_detail_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[order_details] TO  SCHEMA OWNER 
GO

# [dbo].[orders]

In [0]:
/****** Object:  Table [dbo].[orders]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[orders](
	[order_id] [int] IDENTITY(1,1) NOT NULL,
	[user_id] [int] NOT NULL,
	[restaurant_id] [int] NOT NULL,
	[order_date] [datetime] NULL,
	[order_status] [varchar](50) NULL,
	[quantity] [int] NOT NULL,
	[total_amount] [decimal](10, 2) NULL,
	[query_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[order_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[orders] TO  SCHEMA OWNER 
GO

# [dbo].[queries]

In [0]:
/****** Object:  Table [dbo].[queries]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[queries](
	[query_id] [int] IDENTITY(1,1) NOT NULL,
	[user_id] [int] NULL,
	[food_type] [varchar](50) NULL,
	[occasion] [varchar](100) NULL,
	[people] [int] NULL,
	[food_items] [nvarchar](max) NULL,
	[budget] [decimal](10, 2) NULL,
	[event_date] [date] NULL,
	[event_time] [time](7) NULL,
	[additional_info] [nvarchar](max) NULL,
	[status] [varchar](50) NULL,
	[created_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[query_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[queries] TO  SCHEMA OWNER 
GO

# [dbo].[restaurant_feedback]

In [0]:
/****** Object:  Table [dbo].[restaurant_feedback]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[restaurant_feedback](
	[feedback_id] [int] IDENTITY(1,1) NOT NULL,
	[restaurant_id] [int] NOT NULL,
	[hygiene] [int] NULL,
	[packaging] [int] NULL,
	[quality] [int] NULL,
	[delivered_on_time] [int] NULL,
	[comments] [nvarchar](max) NULL,
	[created_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[feedback_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[restaurant_feedback] TO  SCHEMA OWNER 
GO

# [dbo].[restaurant_menu_items]

In [0]:
/****** Object:  Table [dbo].[restaurant_menu_items]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[restaurant_menu_items](
	[item_id] [int] IDENTITY(1,1) NOT NULL,
	[restaurant_id] [int] NOT NULL,
	[item_name] [varchar](255) NOT NULL,
	[item_description] [varchar](max) NULL,
	[price] [decimal](10, 2) NOT NULL,
	[veg_nonveg] [int] NULL,
	[item_image] [varchar](255) NULL,
	[is_active_yn] [int] NULL,
	[average_rating] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[item_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[restaurant_menu_items] TO  SCHEMA OWNER 
GO

# [dbo].[restaurant_queries]

In [0]:
/****** Object:  Table [dbo].[restaurant_queries]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[restaurant_queries](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[query_id] [int] NULL,
	[restaurant_id] [int] NULL,
	[status] [varchar](50) NULL,
	[updated_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[restaurant_queries] TO  SCHEMA OWNER 
GO

# [dbo].[restaurants]

In [0]:
/****** Object:  Table [dbo].[restaurants]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[restaurants](
	[restaurant_id] [int] IDENTITY(1,1) NOT NULL,
	[restaurant_name] [varchar](255) NOT NULL,
	[restaurant_description] [varchar](max) NULL,
	[address] [varchar](255) NULL,
	[contact_no] [varchar](15) NULL,
	[available_days] [varchar](50) NULL,
	[available_time] [varchar](50) NULL,
	[created_at] [datetime] NULL,
	[updated_at] [datetime] NULL,
	[active_yn] [int] NULL,
	[user_id] [int] NULL,
	[average_rating] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[restaurant_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[restaurants] TO  SCHEMA OWNER 
GO

# [dbo].[user_role]

In [0]:
/****** Object:  Table [dbo].[user_role]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[user_role](
	[role_id] [int] IDENTITY(1,1) NOT NULL,
	[role_name] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[role_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[user_role] TO  SCHEMA OWNER 
GO

# [dbo].[users]

In [0]:
/****** Object:  Table [dbo].[users]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[user_id] [int] IDENTITY(1,1) NOT NULL,
	[full_name] [varchar](255) NOT NULL,
	[user_role_id] [int] NOT NULL,
	[dob] [date] NULL,
	[user_phone] [varchar](15) NULL,
	[user_email] [varchar](255) NULL,
	[password] [varchar](255) NOT NULL,
	[profile_image] [varchar](255) NULL,
	[created_at] [datetime] NULL,
	[updated_at] [datetime] NULL,
	[active_yn] [int] NULL,
	[token] [varchar](max) NULL,
	[time_to_expire] [datetime] NULL,
	[username] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[users] TO  SCHEMA OWNER 
GO

# [DF__bids__created_at__1F63A897]

In [0]:
ALTER TABLE [dbo].[bids] ADD  DEFAULT (getdate()) FOR [created_at]
GO

# [DF__bids__status__2057CCD0]

In [0]:
ALTER TABLE [dbo].[bids] ADD  DEFAULT ('Pending') FOR [status]
GO

# [DF__custom_it__creat__336AA144]

In [0]:
ALTER TABLE [dbo].[custom_items] ADD  DEFAULT (getdate()) FOR [created_at]
GO

# [DF__dish_feed__creat__793DFFAF]

In [0]:
ALTER TABLE [dbo].[dish_feedback] ADD  DEFAULT (getdate()) FOR [created_at]
GO

# [DF__forgot_pa__time___5FB337D6]

In [0]:
ALTER TABLE [dbo].[forgot_password_table] ADD  DEFAULT (getdate()) FOR [time_to_expire]
GO

# [DF__orders__order_da__02FC7413]

In [0]:
ALTER TABLE [dbo].[orders] ADD  DEFAULT (getdate()) FOR [order_date]
GO

# [DF__queries__status__5224328E]

In [0]:
ALTER TABLE [dbo].[queries] ADD  DEFAULT ('Pending') FOR [status]
GO

# [DF__queries__created__531856C7]

In [0]:
ALTER TABLE [dbo].[queries] ADD  DEFAULT (getdate()) FOR [created_at]
GO

# [DF__restauran__creat__00DF2177]

In [0]:
ALTER TABLE [dbo].[restaurant_feedback] ADD  DEFAULT (getdate()) FOR [created_at]
GO

# [DF__restauran__veg_n__45F365D3]

In [0]:
ALTER TABLE [dbo].[restaurant_menu_items] ADD  DEFAULT ((0)) FOR [veg_nonveg]
GO

# [DF__restauran__item___46E78A0C]

In [0]:
ALTER TABLE [dbo].[restaurant_menu_items] ADD  DEFAULT ('default.png') FOR [item_image]
GO

# [DF__restauran__is_ac__47DBAE45]

In [0]:
ALTER TABLE [dbo].[restaurant_menu_items] ADD  DEFAULT ((1)) FOR [is_active_yn]
GO

# [DF__restauran__avera__73852659]

In [0]:
ALTER TABLE [dbo].[restaurant_menu_items] ADD  DEFAULT ((0)) FOR [average_rating]
GO

# [DF__restauran__statu__57DD0BE4]

In [0]:
ALTER TABLE [dbo].[restaurant_queries] ADD  DEFAULT ('Pending') FOR [status]
GO

# [DF__restauran__updat__58D1301D]

In [0]:
ALTER TABLE [dbo].[restaurant_queries] ADD  DEFAULT (getdate()) FOR [updated_at]
GO

# [DF__restauran__creat__412EB0B6]

In [0]:
ALTER TABLE [dbo].[restaurants] ADD  DEFAULT (getdate()) FOR [created_at]
GO

# [DF__restauran__updat__4222D4EF]

In [0]:
ALTER TABLE [dbo].[restaurants] ADD  DEFAULT (getdate()) FOR [updated_at]
GO

# [DF__restauran__activ__4316F928]

In [0]:
ALTER TABLE [dbo].[restaurants] ADD  DEFAULT ((1)) FOR [active_yn]
GO

# [DF__restauran__avera__74794A92]

In [0]:
ALTER TABLE [dbo].[restaurants] ADD  DEFAULT ((0)) FOR [average_rating]
GO

# [DF__users__profile_i__3A81B327]

In [0]:
ALTER TABLE [dbo].[users] ADD  DEFAULT ('default.png') FOR [profile_image]
GO

# [DF__users__created_a__3B75D760]

In [0]:
ALTER TABLE [dbo].[users] ADD  DEFAULT (getdate()) FOR [created_at]
GO

# [DF__users__updated_a__3C69FB99]

In [0]:
ALTER TABLE [dbo].[users] ADD  DEFAULT (getdate()) FOR [updated_at]
GO

# [DF__users__active_yn__3D5E1FD2]

In [0]:
ALTER TABLE [dbo].[users] ADD  DEFAULT ((1)) FOR [active_yn]
GO

# [FK_bids_query]

In [0]:
ALTER TABLE [dbo].[bids]  WITH CHECK ADD  CONSTRAINT [FK_bids_query] FOREIGN KEY([query_id])
REFERENCES [dbo].[queries] ([query_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[bids] CHECK CONSTRAINT [FK_bids_query]
GO

# [FK_bids_restaurant]

In [0]:
ALTER TABLE [dbo].[bids]  WITH CHECK ADD  CONSTRAINT [FK_bids_restaurant] FOREIGN KEY([restaurant_id])
REFERENCES [dbo].[restaurants] ([restaurant_id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[bids] CHECK CONSTRAINT [FK_bids_restaurant]
GO

# [FK__custom_it__order__345EC57D]

In [0]:
ALTER TABLE [dbo].[custom_items]  WITH CHECK ADD FOREIGN KEY([order_id])
REFERENCES [dbo].[orders] ([order_id])
ON DELETE CASCADE
GO

# [FK__dish_feed__order__7A3223E8]

In [0]:
ALTER TABLE [dbo].[dish_feedback]  WITH CHECK ADD FOREIGN KEY([order_detail_id])
REFERENCES [dbo].[order_details] ([order_detail_id])
GO

# [FK__forgot_pa__user___60A75C0F]

In [0]:
ALTER TABLE [dbo].[forgot_password_table]  WITH CHECK ADD FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([user_id])
GO

# [FK__forgot_pa__user___619B8048]

In [0]:
ALTER TABLE [dbo].[forgot_password_table]  WITH CHECK ADD FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([user_id])
GO

# [FK__order_det__item___5165187F]

In [0]:
ALTER TABLE [dbo].[order_details]  WITH CHECK ADD FOREIGN KEY([item_id])
REFERENCES [dbo].[restaurant_menu_items] ([item_id])
GO

# [FK__order_det__order__5070F446]

In [0]:
ALTER TABLE [dbo].[order_details]  WITH CHECK ADD FOREIGN KEY([order_id])
REFERENCES [dbo].[orders] ([order_id])
GO

# [FK__orders__query_id__59C55456]

In [0]:
ALTER TABLE [dbo].[orders]  WITH CHECK ADD FOREIGN KEY([query_id])
REFERENCES [dbo].[queries] ([query_id])
GO

# [FK__orders__restaura__03F0984C]

In [0]:
ALTER TABLE [dbo].[orders]  WITH CHECK ADD FOREIGN KEY([restaurant_id])
REFERENCES [dbo].[restaurants] ([restaurant_id])
GO

# [FK__orders__restaura__06CD04F7]

In [0]:
ALTER TABLE [dbo].[orders]  WITH CHECK ADD FOREIGN KEY([restaurant_id])
REFERENCES [dbo].[restaurants] ([restaurant_id])
GO

# [FK__orders__user_id__04E4BC85]

In [0]:
ALTER TABLE [dbo].[orders]  WITH CHECK ADD FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([user_id])
GO

# [FK__orders__user_id__07C12930]

In [0]:
ALTER TABLE [dbo].[orders]  WITH CHECK ADD FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([user_id])
GO

# [FK__queries__user_id__51300E55]

In [0]:
ALTER TABLE [dbo].[queries]  WITH CHECK ADD FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([user_id])
ON DELETE CASCADE
GO

# [FK__restauran__resta__01D345B0]

In [0]:
ALTER TABLE [dbo].[restaurant_feedback]  WITH CHECK ADD FOREIGN KEY([restaurant_id])
REFERENCES [dbo].[restaurants] ([restaurant_id])
ON DELETE CASCADE
GO

# [FK__restauran__resta__48CFD27E]

In [0]:
ALTER TABLE [dbo].[restaurant_menu_items]  WITH CHECK ADD FOREIGN KEY([restaurant_id])
REFERENCES [dbo].[restaurants] ([restaurant_id])
GO

# [FK__restauran__query__55F4C372]

In [0]:
ALTER TABLE [dbo].[restaurant_queries]  WITH CHECK ADD FOREIGN KEY([query_id])
REFERENCES [dbo].[queries] ([query_id])
GO

# [FK__restauran__resta__56E8E7AB]

In [0]:
ALTER TABLE [dbo].[restaurant_queries]  WITH CHECK ADD FOREIGN KEY([restaurant_id])
REFERENCES [dbo].[restaurants] ([restaurant_id])
GO

# [FK__restauran__user___151B244E]

In [0]:
ALTER TABLE [dbo].[restaurants]  WITH CHECK ADD FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([user_id])
GO

# [FK__users__user_role__398D8EEE]

In [0]:
ALTER TABLE [dbo].[users]  WITH CHECK ADD FOREIGN KEY([user_role_id])
REFERENCES [dbo].[user_role] ([role_id])
GO

# [CK__custom_it__quant__318258D2]

In [0]:
ALTER TABLE [dbo].[custom_items]  WITH CHECK ADD CHECK  (([quantity]>(0)))
GO

# [CK__dish_feed__ratin__7849DB76]

In [0]:
ALTER TABLE [dbo].[dish_feedback]  WITH CHECK ADD CHECK  (([rating]>=(1) AND [rating]<=(5)))
GO

# [CK__restauran__deliv__7FEAFD3E]

In [0]:
ALTER TABLE [dbo].[restaurant_feedback]  WITH CHECK ADD CHECK  (([delivered_on_time]>=(1) AND [delivered_on_time]<=(5)))
GO

# [CK__restauran__hygie__7D0E9093]

In [0]:
ALTER TABLE [dbo].[restaurant_feedback]  WITH CHECK ADD CHECK  (([hygiene]>=(1) AND [hygiene]<=(5)))
GO

# [CK__restauran__packa__7E02B4CC]

In [0]:
ALTER TABLE [dbo].[restaurant_feedback]  WITH CHECK ADD CHECK  (([packaging]>=(1) AND [packaging]<=(5)))
GO

# [CK__restauran__quali__7EF6D905]

In [0]:
ALTER TABLE [dbo].[restaurant_feedback]  WITH CHECK ADD CHECK  (([quality]>=(1) AND [quality]<=(5)))
GO

# [dbo].[AddMenuItem]

In [0]:
/****** Object:  StoredProcedure [dbo].[AddMenuItem]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[AddMenuItem]
    @user_id INT,
    @item_name NVARCHAR(255),
    @item_description NVARCHAR(MAX),
    @price DECIMAL(10,2),
    @veg_nonveg NVARCHAR(10) -- Assuming 'Veg' or 'Non-Veg'
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @restaurant_id INT;

    -- Get restaurant_id for the given user_id (owner)
    SELECT @restaurant_id = restaurant_id 
    FROM restaurants 
    WHERE user_id = @user_id;

    -- Check if a restaurant exists for this user_id
    IF @restaurant_id IS NOT NULL
    BEGIN
        -- Insert the new menu item
        INSERT INTO [restaurant_menu_items] (restaurant_id, item_name, item_description, price, veg_nonveg, is_active_yn, average_rating)
        VALUES (@restaurant_id, @item_name, @item_description, @price, @veg_nonveg, 1, 0);

        PRINT 'Menu item added successfully!';
    END
    ELSE
    BEGIN
        -- Raise an error if no restaurant is found
        THROW 50000, 'No restaurant found for the given user_id', 1;
    END
END;
GO
ALTER AUTHORIZATION ON [dbo].[AddMenuItem] TO  SCHEMA OWNER 
GO

# [dbo].[InsertOrderAndDetails]

In [0]:
/****** Object:  StoredProcedure [dbo].[InsertOrderAndDetails]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[InsertOrderAndDetails](
    @user_id INT,
    @restaurant_id INT,
    @order_date DATETIME,
    @order_status VARCHAR(50),
    @quantity INT,
    @total_amount DECIMAL(10,2),
    @cart_items NVARCHAR(MAX)
)
AS
BEGIN
    DECLARE @order_id INT;
    
    BEGIN TRANSACTION;

    -- Insert into orders table
    INSERT INTO orders (user_id, restaurant_id, order_date, order_status, quantity, total_amount)
    VALUES (@user_id, @restaurant_id, @order_date, @order_status, @quantity, @total_amount);

    -- Get generated order ID
    SET @order_id = SCOPE_IDENTITY();

    IF @order_id IS NULL OR @order_id = 0
    BEGIN
        ROLLBACK TRANSACTION;
        RETURN -1;
    END

    -- Insert into order_details
    INSERT INTO order_details (order_id, item_id, quantity, price)
    SELECT 
        @order_id, 
        JSON_VALUE(cart.value, '$.item_id') AS item_id,
        JSON_VALUE(cart.value, '$.quantity') AS quantity,
        JSON_VALUE(cart.value, '$.price') AS price
    FROM OPENJSON(@cart_items) AS cart;

    COMMIT TRANSACTION;
    RETURN @order_id;
END;
GO
ALTER AUTHORIZATION ON [dbo].[InsertOrderAndDetails] TO  SCHEMA OWNER 
GO

# [dbo].[PlaceOrderFromBid]

In [0]:
/****** Object:  StoredProcedure [dbo].[PlaceOrderFromBid]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[PlaceOrderFromBid]
    @bid_id INT
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @query_id INT, @restaurant_id INT, @user_id INT, @food_items NVARCHAR(MAX),  @price INT,
            @order_id INT, @quantity INT, @total_amount DECIMAL(10,2);

    -- Start transaction for data consistency
    BEGIN TRANSACTION;
    
    BEGIN TRY
        -- 1️⃣ Get Query ID and Restaurant ID from Bid
        SELECT @query_id = query_id, @restaurant_id = restaurant_id , @price = bid_price
        FROM bids
        WHERE bid_id = @bid_id;

        -- 2️⃣ Get User ID, food items, and quantity from Queries table
        SELECT @user_id = user_id, @food_items = food_items, @quantity = people
        FROM queries
        WHERE query_id = @query_id;

        -- 3️⃣ Create Order
        INSERT INTO orders (user_id, restaurant_id, order_date, order_status, query_id, quantity, total_amount)
        VALUES (@user_id, @restaurant_id, GETDATE(), 'Pending', @query_id, @quantity, @price);

        SET @order_id = SCOPE_IDENTITY(); -- Get newly created order ID

        -- 4️⃣ Process each food item
        DECLARE @item_name NVARCHAR(255), @existing_item_id INT, @pricee DECIMAL(10,2);

        DECLARE food_cursor CURSOR FOR 
        SELECT value FROM STRING_SPLIT(@food_items, ','); -- Splitting food items

        OPEN food_cursor;
        
        FETCH NEXT FROM food_cursor INTO @item_name;
        WHILE @@FETCH_STATUS = 0
        BEGIN
            -- Reset variables for each item
            SET @existing_item_id = NULL;
            SET @pricee = NULL;

            PRINT 'Processing food item: ' + @item_name; -- Debugging

            -- 4.1️⃣ Check if item exists in restaurant's menu
            SELECT @existing_item_id = item_id, @pricee = price
            FROM restaurant_menu_items
            WHERE item_name = @item_name AND restaurant_id = @restaurant_id;

            IF @existing_item_id IS NOT NULL
            BEGIN
                -- 4.2️⃣ Insert into order_details if item exists
                INSERT INTO order_details (order_id, item_id, quantity, price)
                VALUES (@order_id, @existing_item_id, @quantity, @pricee);
            END
            ELSE
            BEGIN
                -- 4.3️⃣ Insert into restaurant_menu_items first
                INSERT INTO restaurant_menu_items (restaurant_id, item_name, price)
                VALUES (@restaurant_id, @item_name, 100); -- Default price 100

                SET @existing_item_id = SCOPE_IDENTITY(); -- Get newly created menu item ID

                -- 4.4️⃣ Insert into order_details referencing newly added item
                INSERT INTO order_details (order_id, item_id, quantity, price)
                VALUES (@order_id, @existing_item_id, @quantity, 100);
            END

            -- Fetch next item
            FETCH NEXT FROM food_cursor INTO @item_name;
        END

        CLOSE food_cursor;
        DEALLOCATE food_cursor;

        -- 5️⃣ Update total order amount
        SELECT @total_amount = COALESCE(SUM(price * quantity), 0)
        FROM order_details
        WHERE order_id = @order_id;

        UPDATE bids 
        SET status = 'Accepted'
        WHERE bid_id = @bid_id;

        UPDATE orders
        SET total_amount = @total_amount
        WHERE order_id = @order_id;

        -- 6️⃣ Update order status to 'Processed'
        UPDATE orders
        SET order_status = 'Processed'
        WHERE order_id = @order_id;

        UPDATE queries
        SET status = 'Accepted'
        WHERE query_id = @query_id;

        -- Commit the transaction
        COMMIT TRANSACTION;

    END TRY
    BEGIN CATCH
        -- Rollback in case of any failure
        ROLLBACK TRANSACTION;
        PRINT 'Error Occurred: ' + ERROR_MESSAGE();
    END CATCH
END;
GO
ALTER AUTHORIZATION ON [dbo].[PlaceOrderFromBid] TO  SCHEMA OWNER 
GO

# [dbo].[sp_DecideQuery]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_DecideQuery]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE     PROCEDURE [dbo].[sp_DecideQuery]
    @query_id INT,
    @status VARCHAR(50)  -- 'accepted' or 'rejected'
AS
BEGIN
    SET NOCOUNT ON;

    -- Update the restaurant_queries table
    UPDATE restaurant_queries
    SET status = @status, updated_at = GETDATE()
    WHERE query_id = @query_id  ;

   
        UPDATE queries
        SET status = @status 
        WHERE query_id = @query_id;

    return 1
END;
GO
ALTER AUTHORIZATION ON [dbo].[sp_DecideQuery] TO  SCHEMA OWNER 
GO

# [dbo].[sp_fetch_restaurant_details]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_fetch_restaurant_details]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE     PROCEDURE [dbo].[sp_fetch_restaurant_details]
    @restaurant_id INT
AS
BEGIN
    SELECT 
        *
    FROM 
        restaurants r inner join users u on r.user_id = u.user_id
    WHERE 
        restaurant_id = @restaurant_id;
END;
GO
ALTER AUTHORIZATION ON [dbo].[sp_fetch_restaurant_details] TO  SCHEMA OWNER 
GO

# [dbo].[sp_generate_token]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_generate_token]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_generate_token] 
    @email VARCHAR(100)
AS
BEGIN
    DECLARE @userid INT
	Declare @token NVARCHAR(MAX) = NEWID();
    SELECT @userid = user_id FROM users WHERE user_email = @email;
    INSERT INTO dbo.forgot_password_table (user_id, token, time_to_expire) 
    VALUES (@userid, @token, DATEADD(mi, 15, GETDATE()));
	
	select @token As GeneratedToken 
END
GO
ALTER AUTHORIZATION ON [dbo].[sp_generate_token] TO  SCHEMA OWNER 
GO

# [dbo].[sp_get_order_details]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_get_order_details]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE     PROCEDURE [dbo].[sp_get_order_details]
    @order_id INT 
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        o.order_id,
        o.order_date,
        o.order_status,
        o.quantity AS total_quantity,
        o.total_amount AS total_amount,

        -- User Details
        u.user_id,
        u.full_name AS customer_name,
        u.user_email,
        u.user_phone,

        -- Restaurant Details
        r.restaurant_id,
        r.restaurant_name,
        r.address AS restaurant_address,
        r.contact_no AS restaurant_contact,

        -- JSON Array of Items
        (
            SELECT 
			oi.order_detail_id,
                oi.item_id,
                mi.item_name,
                mi.item_description,
                mi.price AS item_price,
                oi.quantity AS item_quantity
            FROM order_details oi
            JOIN restaurant_menu_items mi ON oi.item_id = mi.item_id
            WHERE oi.order_id = o.order_id
            FOR JSON PATH
        ) AS order_items_json

    FROM orders o
    JOIN users u ON o.user_id = u.user_id
    JOIN restaurants r ON o.restaurant_id = r.restaurant_id
    WHERE o.order_id = @order_id;
END;
GO
ALTER AUTHORIZATION ON [dbo].[sp_get_order_details] TO  SCHEMA OWNER 
GO

# [dbo].[sp_get_queries]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_get_queries]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

  CREATE   procedure [dbo].[sp_get_queries]
  AS
  BEGIn 
  SELECT TOP (1000) [query_id]
      ,q.[user_id]
      ,q.[food_type]
      ,q.[occasion]
      ,q.[people]
      ,q.[food_items]
      ,q.[budget]
      ,q.[event_date]
      ,q.[event_time]
      ,q.[additional_info]
      ,q.[status]
      ,q.[created_at],
	  u.user_email,u.full_name
  FROM [smartserve].[dbo].[queries] q inner join dbo.users u on q.user_id = u.user_id 
  end
GO
ALTER AUTHORIZATION ON [dbo].[sp_get_queries] TO  SCHEMA OWNER 
GO

# [dbo].[sp_get_restaurant_menu]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_get_restaurant_menu]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE     PROCEDURE [dbo].[sp_get_restaurant_menu]
    @restaurant_id INT
AS
BEGIN
    SELECT item_id, item_name, item_description, price, veg_nonveg, item_image, is_active_yn
    FROM restaurant_menu_items
    WHERE restaurant_id = @restaurant_id AND is_active_yn = 1
END
GO
ALTER AUTHORIZATION ON [dbo].[sp_get_restaurant_menu] TO  SCHEMA OWNER 
GO

# [dbo].[sp_get_restaurants]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_get_restaurants]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE       PROCEDURE [dbo].[sp_get_restaurants]
AS
BEGIN
    SELECT 
        *
    FROM 
        restaurants r inner join users u on r.user_id = u.user_id
    WHERE r.active_yn = 1
END
GO
ALTER AUTHORIZATION ON [dbo].[sp_get_restaurants] TO  SCHEMA OWNER 
GO

# [dbo].[sp_GetQueriesForRestaurant]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_GetQueriesForRestaurant]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE     PROCEDURE [dbo].[sp_GetQueriesForRestaurant]
    @restaurant_id INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        q.query_id,
        q.food_type,
        q.occasion,
        q.people,
        q.food_items,
        q.budget,
        q.event_date,
        q.event_time,
        q.additional_info,
        q.status AS query_status,
        q.created_at,
        u.user_id,
        u.full_name,
        u.user_phone,
        u.user_email
    FROM 
        restaurant_queries rq
    JOIN 
        queries q ON rq.query_id = q.query_id
    JOIN 
        users u ON q.user_id = u.user_id
    WHERE 
        rq.restaurant_id = @restaurant_id and rq.status != 'accepted'
    ORDER BY 
        q.created_at DESC; -- Show latest queries first
END;
GO
ALTER AUTHORIZATION ON [dbo].[sp_GetQueriesForRestaurant] TO  SCHEMA OWNER 
GO

# [dbo].[sp_GetQueriesForUser]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_GetQueriesForUser]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE         PROCEDURE [dbo].[sp_GetQueriesForUser]
    @user_id INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        q.query_id,
        q.food_type,
        q.occasion,
        q.people,
        q.food_items,
        q.budget,
        q.event_date,
        q.event_time,
        q.additional_info,
        q.status AS query_status,
        q.created_at,
        u.user_id,
        u.full_name,
        u.user_phone,
        u.user_email
    FROM 
       
        queries q 
    JOIN 
        users u ON q.user_id = u.user_id
    WHERE 
        q.user_id = @user_id
		ORDER BY 
        q.created_at DESC; -- Show latest queries first
END;
GO
ALTER AUTHORIZATION ON [dbo].[sp_GetQueriesForUser] TO  SCHEMA OWNER 
GO

# [dbo].[sp_InsertQuery]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_InsertQuery]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[sp_InsertQuery]
    @user_id INT,
    @food_type VARCHAR(50),
    @occasion VARCHAR(50),
    @people INT,
    @food_items NVARCHAR(MAX),
    @budget DECIMAL(10,2),
    @event_date DATE,
    @event_time TIME,
    @additional_info NVARCHAR(MAX)
    
AS
BEGIN
    
	SET NOCOUNT ON;

    INSERT INTO queries (user_id, food_type, occasion, people, food_items, budget, event_date, event_time, additional_info, status, created_at)
    VALUES (@user_id, @food_type, @occasion, @people, @food_items, @budget, @event_date, @event_time, @additional_info, 'pending', GETDATE());
	DECLARE @query_id INT;
    -- Get the newly inserted query ID
    SET @query_id = SCOPE_IDENTITY();

    -- Insert into restaurant_queries so all restaurants can see it
    INSERT INTO restaurant_queries (query_id, restaurant_id, status)
    SELECT @query_id, restaurant_id, 'pending' FROM restaurants;
END;
GO
ALTER AUTHORIZATION ON [dbo].[sp_InsertQuery] TO  SCHEMA OWNER 
GO

# [dbo].[sp_login_user]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_login_user]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE                 PROCEDURE [dbo].[sp_login_user]
    @username VARCHAR(100),
    @password NVARCHAR(MAX)
AS
BEGIN
    DECLARE @count INT;
            SELECT @count = COUNT(1)
            FROM dbo.users
            WHERE username = @username
                AND password = @password 
    IF @count = 1
    BEGIN
	UPDATE dbo.users 
	SET token = NEWID(),
	time_to_expire =  DATEADD(MI, 30, GETDATE())
	where username = @username
	
        SELECT *
        FROM dbo.users
        WHERE username = @username
        AND password = @password;
        
    END
    ELSE
    BEGIN
        SELECT 0 as validYN;
    END
END

GO
ALTER AUTHORIZATION ON [dbo].[sp_login_user] TO  SCHEMA OWNER 
GO

# [dbo].[sp_register_restaurant]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_register_restaurant]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[sp_register_restaurant]
    @full_name VARCHAR(255),
    @password NVARCHAR(MAX),
    @user_email VARCHAR(255),
    @user_phone VARCHAR(15),
    @dob VARCHAR(255),
    @restaurant_name VARCHAR(255),           -- New parameter for restaurant name
    @restaurant_description VARCHAR(MAX),    -- New parameter for restaurant description
    @address VARCHAR(255),                   -- New parameter for restaurant address
    @contact_no VARCHAR(15),                 -- New parameter for restaurant contact number
    @available_days VARCHAR(50),             -- New parameter for available days
    @available_time VARCHAR(50),             -- New parameter for available time
    @token VARCHAR(MAX) = NULL,              -- Optional token (default NULL)
    @time_to_expire DATETIME = NULL          -- Optional expiration (default NULL)
AS
BEGIN
    BEGIN TRY
        -- Check if the user already exists (based on email or phone number)
        IF EXISTS (SELECT 1 FROM dbo.users WHERE user_email = @user_email OR user_phone = @user_phone)
        BEGIN
            RAISERROR('User with this email or phone number already exists', 16, 1);
            RETURN;
        END

        DECLARE @username VARCHAR(255);
        DECLARE @base_username VARCHAR(255);
        DECLARE @username_attempt VARCHAR(255);
        DECLARE @counter INT = 0;

        -- Generate base username
        SET @base_username = LOWER(LEFT(@full_name, CHARINDEX(' ', @full_name) - 1)) + 
                             LOWER(RIGHT(@full_name, LEN(@full_name) - CHARINDEX(' ', @full_name)));

        -- Check if the username exists and handle conflicts
        SET @username_attempt = @base_username;

        WHILE EXISTS (SELECT 1 FROM dbo.users WHERE username = @username_attempt)
        BEGIN
            SET @counter = @counter + 1;
            SET @username_attempt = @base_username + CAST(@counter AS VARCHAR(10));
        END

        SET @username = @username_attempt;

        -- Insert new user
        INSERT INTO dbo.users
            (full_name, password, username, user_email, user_phone, dob, user_role_id, created_at, updated_at, active_yn, token, time_to_expire)
        VALUES
            (@full_name, @password, @username, @user_email, @user_phone, CONVERT(DATE, @dob, 120), 2, GETDATE(), GETDATE(), 1, @token, @time_to_expire);

        DECLARE @user_id INT;
        SET @user_id = SCOPE_IDENTITY(); -- Capture the newly inserted user's ID

        -- Insert new restaurant details linked to the user
        INSERT INTO dbo.restaurants
            (restaurant_name, restaurant_description, address, contact_no, available_days, available_time, created_at, updated_at, active_yn, user_id)
        VALUES
            (@restaurant_name, @restaurant_description, @address, @contact_no, @available_days, @available_time, GETDATE(), GETDATE(), 1, @user_id);

        -- Return success message
        SELECT 'User and restaurant registered successfully' AS message;
    END TRY
    BEGIN CATCH
        -- Handle errors and return error message
        SELECT ERROR_MESSAGE() AS message;
    END CATCH
END
GO
ALTER AUTHORIZATION ON [dbo].[sp_register_restaurant] TO  SCHEMA OWNER 
GO

# [dbo].[sp_register_user]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_register_user]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE       PROCEDURE [dbo].[sp_register_user]
    @full_name VARCHAR(255),
	    @password NVARCHAR(MAX),
    @user_email VARCHAR(255),
    @user_phone VARCHAR(15),
    @dob VARCHAR(255),
    @token VARCHAR(MAX) = NULL,            -- Optional token (default NULL)
    @time_to_expire DATETIME = NULL        -- Optional expiration (default NULL)
AS
BEGIN
    -- Error handling
    BEGIN TRY
     
		  DECLARE @username VARCHAR(255);
    DECLARE @base_username VARCHAR(255);
    DECLARE @username_attempt VARCHAR(255);
    DECLARE @counter INT = 0;
		  -- Generate base username by concatenating the first letter of first name with the last name
    SET @base_username = LOWER(LEFT(@full_name, CHARINDEX(' ', @full_name) - 1)) + 
                         LOWER(RIGHT(@full_name, LEN(@full_name) - CHARINDEX(' ', @full_name)));

    -- Check if this username already exists
    SET @username_attempt = @base_username;

    WHILE EXISTS (SELECT 1 FROM dbo.users WHERE username = @username_attempt)
    BEGIN
        -- Increment the counter and append it to the base username
        SET @counter = @counter + 1;
        SET @username_attempt = @base_username + CAST(@counter AS VARCHAR(10));
    END

    -- Set the final username
    SET @username = @username_attempt;
        -- Insert new user with default values where needed
        INSERT INTO dbo.users
            (full_name, password, username ,user_email, user_phone, dob, user_role_id, created_at, updated_at, active_yn, token, time_to_expire)
        VALUES
            (@full_name, @password,@username, @user_email, @user_phone,  CONVERT(DATE, @dob, 120) , 1, GETDATE(), GETDATE(), 1, @token, @time_to_expire);

        -- Return success message
        SELECT 'User registered successfully' AS message;
    END TRY
    BEGIN CATCH
        -- Handle errors and return error message
        SELECT ERROR_MESSAGE() AS message;
    END CATCH
END
GO
ALTER AUTHORIZATION ON [dbo].[sp_register_user] TO  SCHEMA OWNER 
GO

# [update_dish_rating]

In [0]:
/****** Object:  Trigger [dbo].[update_dish_rating]    Script Date: 31-03-2025 03:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER [dbo].[update_dish_rating]
ON [dbo].[dish_feedback]
AFTER INSERT
AS
BEGIN
    UPDATE restaurant_menu_items
    SET average_rating = (
        SELECT AVG(rating)
        FROM dish_feedback
        WHERE order_detail_id IN (
            SELECT order_detail_id 
            FROM order_details 
            WHERE item_id = restaurant_menu_items.item_id
        )
    )
    WHERE item_id IN (
        SELECT item_id 
        FROM order_details 
        WHERE order_detail_id IN (SELECT order_detail_id FROM inserted)
    );
END;

GO
ALTER TABLE [dbo].[dish_feedback] ENABLE TRIGGER [update_dish_rating]
GO

# [update_restaurant_rating]

In [0]:
/****** Object:  Trigger [dbo].[update_restaurant_rating]    Script Date: 31-03-2025 03:06:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER [dbo].[update_restaurant_rating]
ON [dbo].[restaurant_feedback]
AFTER INSERT
AS
BEGIN
    UPDATE restaurants
    SET average_rating = (
        SELECT AVG((hygiene + packaging + quality + delivered_on_time) / 4.0)
        FROM restaurant_feedback
        WHERE restaurant_id = restaurants.restaurant_id
    )
    WHERE restaurant_id IN (SELECT restaurant_id FROM inserted);
END;
GO
ALTER TABLE [dbo].[restaurant_feedback] ENABLE TRIGGER [update_restaurant_rating]
GO